### ISSUE TITLE
cant decipher errors

### ISSUE THREAD

**Issue by Samuel-Morgan-Tyghe** [imjuni/ctix#163]
Example
```

vegas-MacBook-Pro:front-client sam$ npx ctix build --mode create -p .ctirc --start-from ./packages/vega-api/src
✔ /Users/sam/Documents/GitHub/front-client/tsconfig.json loading complete!
✔ analysis export statements completed!
    file [                                        ] 0% | 0/1326
vegas-MacBook-Pro:front-client sam$ 

  at getExportedKind (node_modules/ctix/src/compilers/getExportedKind.ts:10:21)
  at node_modules/ctix/src/compilers/getExportStatement.ts:47:20
  at Array.map (<anonymous>)
  at getExportStatement (node_modules/ctix/src/compilers/getExportStatement.ts:44:6)
  at node_modules/ctix/src/modules/commands/creating.ts:117:29
  at async Promise.all (index 896)
  at creating (node_modules/ctix/src/modules/commands/creating.ts:112:5)
  at building (node_modules/ctix/src/modules/commands/building.ts:8:3)
  at buildCommandCode (node_modules/ctix/src/cli/commands/buildCommand.ts:12:3)
  at buildCommand (node_modules/ctix/src/cli/commands/buildCommand.ts:21:5)

    file [■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■] 100% | 1326/1326
```

**Comment by imjuni** [comment]
@Samuel-Morgan-Tyghe Hi,

This issue is raised from a statement that cannot be parsed. Could you provide a reproducible repo?

**Comment by imjuni** [comment]
@Samuel-Morgan-Tyghe Hi,

I improve error message when encounter cannot support syntax. Use v2.7.0 and re-open or create new issue.

Thank you :)

**Comment by Samuel-Morgan-Tyghe** [comment]
This happen when initialising a new projetct with all features option
